version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: wikijs
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wikijs:
    image: requarks/wiki:latest
    container_name: wikijs
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: meu_usuario
      DB_PASS: senha
      DB_NAME: wikijs
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
